#!/usr/bin/env bash
# Bootstrap a local Supabase stack for Optigo dev and load a runnable schema.
#
# This is a ONE-OFF helper for local development (e.g. Cursor Cloud VMs). It is
# NOT part of the automatic dependency-refresh update script. Prerequisites that
# are assumed to already be installed on the machine:
#   * Docker (daemon running or startable)
#   * Supabase CLI (`supabase`)
#   * Node deps installed (`npm install`)
#
# Safe to re-run: it recreates the public schema from scratch (DESTRUCTIVE to
# any data in the local dev DB only).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "==> Ensuring Docker daemon is running"
if ! docker info >/dev/null 2>&1; then
  sudo nohup dockerd >/tmp/dockerd.log 2>&1 &
  for _ in $(seq 1 30); do docker info >/dev/null 2>&1 && break; sleep 1; done
  sudo chmod 666 /var/run/docker.sock 2>/dev/null || true
fi

echo "==> Starting local Supabase (idempotent)"
supabase start

echo "==> Discovering local Supabase credentials"
API_URL="$(supabase status -o env 2>/dev/null | sed -n 's/^API_URL="\(.*\)"$/\1/p')"
ANON_KEY="$(supabase status -o env 2>/dev/null | sed -n 's/^ANON_KEY="\(.*\)"$/\1/p')"
SERVICE_ROLE_KEY="$(supabase status -o env 2>/dev/null | sed -n 's/^SERVICE_ROLE_KEY="\(.*\)"$/\1/p')"
DB_URL="$(supabase status -o env 2>/dev/null | sed -n 's/^DB_URL="\(.*\)"$/\1/p')"

echo "==> Writing .env.local"
cat > .env.local <<EOF
# Local development env (local Supabase). Generated by scripts/setup-local-supabase.sh
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_URL=${API_URL}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DATABASE_URL=${DB_URL}
EOF

echo "==> Loading dev schema into local database"
DB_CONTAINER="$(docker ps --format '{{.Names}}' | grep -m1 'supabase_db' || true)"
if [ -z "$DB_CONTAINER" ]; then
  echo "ERROR: could not find supabase_db container" >&2
  exit 1
fi
docker exec -i "$DB_CONTAINER" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -q < scripts/dev-local-schema.sql

echo "==> Done. Start the app with: npm run dev  (http://localhost:3000)"
echo "    Then register a clinic at /register (or POST /api/auth/register)."
